services:
  # Database MySQL
  mysql:
    image: mysql:8.0
    container_name: assignment_mysql
    restart: always
    environment:
      MYSQL_DATABASE: assignment_ptes
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: assignment_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Aplikasi Go
  app:
    build: .
    container_name: assignment_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_URL=user:password@tcp(mysql:3306)/assignment_ptes?parseTime=true
      - REDIS_URL=redis:6379
      - PORT=3000

volumes:
  mysql_data:
  redis_data: